name: Create Container

on:
  workflow_dispatch:
    inputs:
      ae-core-version:
        description: 'Valid metaeffekt-core version tag.'
        required: true
        type: string
      ae-artifact-analysis-version:
        description: 'Valid metaeffekt-artifact-analysis version tag.'
        required: true
        type: string
      ae-kontinuum-version:
        description: 'Valid metaeffekt-kontinuum version tag.'
        default: main
        required: true
        type: string
      ae-workbench-version:
        description: 'Valid metaeffekt-workbench version tag.'
        default: main
        required: true
        type: string

env:
  IMAGE_NAME: metaeffekt-kontinuum-runtime
  MIRROR_URL: "https://metaeffekt.com/mirror/ae-vulnerability-mirror/ae-mirror-index_gen5-external.tar.gz"
  MIRROR_NAME: "ae-mirror-index_gen5-external.tar.gz"

jobs:
  create-container:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure git
        shell: bash
        run: |
          git config --local user.email "github-actions[bot]@metaeffekt.com"
          git config --local user.name "github-actions[bot]"

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '8'

      - name: Checkout core
        uses: actions/checkout@v6
        with:
          repository: 'org-metaeffekt/metaeffekt-core'
          ref: ${{ inputs.ae-core-version }}
          path: 'metaeffekt-core'

      - name: Checkout artifact-analysis
        uses: actions/checkout@v6
        with:
          repository: 'org-metaeffekt/metaeffekt-artifact-analysis'
          token: ${{ secrets.ARTIFACT_ANALYSIS_ACCESS_TOKEN }}
          ref: ${{ inputs.ae-artifact-analysis-version }}
          path: 'metaeffekt-artifact-analysis'

      - name: Checkout kontinuum
        uses: actions/checkout@v6
        with:
          repository: 'org-metaeffekt/metaeffekt-kontinuum'
          ref: ${{ inputs.ae-kontinuum-version }}
          path: 'metaeffekt-kontinuum'

      - name: Checkout workbench
        uses: actions/checkout@v6
        with:
          repository: 'org-metaeffekt/metaeffekt-workbench'
          ref: ${{ inputs.ae-workbench-version }}
          path: 'metaeffekt-workbench'

      - name: Build core
        shell: bash
        run: |
          cd metaeffekt-core
          mvn clean install -DskipTests

      - name: Build artifact-analysis
        shell: bash
        run: |
          cd metaeffekt-artifact-analysis
          mvn clean install -DskipTests

      - name: Create external.rc file
        run: |
          touch ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "EXTERNAL_WORKBENCH_DIR=${{ github.workspace }}/metaeffekt-workbench" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "EXTERNAL_VULNERABILITY_MIRROR_DIR=${{ github.workspace }}/metaeffekt-kontinuum/.mirror" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "EXTERNAL_VULNERABILITY_MIRROR_URL=${{ env.MIRROR_URL }}" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "EXTERNAL_VULNERABILITY_MIRROR_NAME=${{ env.MIRROR_NAME }}" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "NVD_API_KEY=${{ secrets.NVD_API_KEY }}" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "AE_CORE_VERSION=${{ inputs.ae-core-version }}" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc
          echo "AE_ARTIFACT_ANALYSIS_VERSION=${{ inputs.ae-artifact-analysis-version }}" >> ${{ github.workspace }}/metaeffekt-kontinuum/external.rc

      - name: Build kontinuum
        shell: bash
        run: |
          ./metaeffekt-kontinuum/tests/scripts/pipelines/001_remote.sh

      - name: Prepare selective maven dependencies
        shell: bash
        run: |
          mkdir -p local-maven-repo/com/metaeffekt
          mkdir -p local-maven-repo/org/metaeffekt
          mkdir -p local-maven-repo/org/jetbrains/kotlin 
          mkdir -p local-maven-repo/org/apache/jena
          cp -r /home/runner/.m2/repository/com/metaeffekt/. local-maven-repo/com/metaeffekt
          cp -r /home/runner/.m2/repository/org/metaeffekt/. local-maven-repo/org/metaeffekt
          cp -r /home/runner/.m2/repository/org/jetbrains/kotlin/. local-maven-repo/org/jetbrains/kotlin
          cp -r /home/runner/.m2/repository/org/apache/jena/. local-maven-repo/org/apache/jena

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'metaeffekt'
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (multi-platform optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 'metaeffekt/${{ env.IMAGE_NAME }}'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          push: false
          file: ${{ github.workspace }}/container/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-image
          path: /tmp/image.tar