name: Create Container

on:
  workflow_dispatch:
    inputs:
      ae-core-version:
        description: 'Valid metaeffekt-core version tag.'
        required: true
        type: string
      ae-artifact-analysis-version:
        description: 'Valid metaeffekt-artifact-analysis version tag.'
        required: true
        type: string
      ae-kontinuum-version:
        description: 'Valid metaeffekt-kontinuum version tag.'
        default: main
        required: true
        type: string

env:
  IMAGE_NAME: metaeffekt-kontinuum-runtime

jobs:
  create-container:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maven
        run: |
          MVN_VER=3.9.11
          wget -q https://downloads.apache.org/maven/maven-3/${MVN_VER}/binaries/apache-maven-${MVN_VER}-bin.tar.gz
          sudo tar -xzf apache-maven-${MVN_VER}-bin.tar.gz -C /opt/
          sudo mv /opt/apache-maven-${MVN_VER} /opt/maven
          echo "/opt/maven/bin" >> "$GITHUB_PATH"

      - name: Checkout required repositories
        run: |
          git clone https://github.com/org-metaeffekt/metaeffekt-kontinuum.git ${{ github.workspace }}/metaeffekt-kontinuum
          cd ${{ github.workspace }}/metaeffekt-kontinuum
          git checkout ${{ inputs.ae-kontinuum-version }}
          git clone https://github.com/org-metaeffekt/metaeffekt-core.git ${{ github.workspace }}/metaeffekt-core
          cd ${{ github.workspace }}/metaeffekt-core
          git checkout ${{ inputs.ae-core-version }}
          git clone https://github.com/org-metaeffekt/metaeffekt-artifact-analysis.git ${{ github.workspace }}/metaeffekt-artifact-analysis
          cd ${{ github.workspace }}/metaeffekt-artifact-analysis
          git checkout ${{ inputs.ae-artifact-analysis-version }}

      - name: Build core
        shell: bash
        run: |
          cd metaeffekt-core
          mvn clean install -DskipTests

      - name: Build artifact-analysis
        shell: bash
        run: |
          cd metaeffekt-artifact-analysis
          mvn clean install -DskipTests

      - name: Build kontinuum
        shell: bash
        run: |
          ./metaeffekt-kontinuum/tests/scripts/pipelines/001_remote.sh

      - name: Prepare selective maven dependencies
        shell: bash
        run: |
          mkdir -p local-maven-repo/com/metaeffekt
          mkdir -p local-maven-repo/org/metaeffekt
          mkdir -p local-maven-repo/org/jetbrains/kotlin 
          mkdir -p local-maven-repo/org/apache/jena
          cp -r /home/runner/.m2/repository/com/metaeffekt/. local-maven-repo/com/metaeffekt
          cp -r /home/runner/.m2/repository/org/metaeffekt/. local-maven-repo/org/metaeffekt
          cp -r /home/runner/.m2/repository/org/jetbrains/kotlin/. local-maven-repo/org/jetbrains/kotlin
          cp -r /home/runner/.m2/repository/org/apache/jena/. local-maven-repo/org/apache/jena

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: metaeffekt
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (multi-platform optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          push: false
          file: ${{ github.workspace }}/container/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-image
          path: /tmp/image.tar


          
